### ISSUE TITLE
Config Read Shell Doesn't Seem to Properly Get the Debug Setting From the Config file

### ISSUE THREAD

**Issue by jtyost2** [loadsys/CakePHP-ConfigReadShell#2]
Using this command `./bin/cake config_read.config_read debug`
And running this `grep -i "Configure::write('debug'" ./Config/*` produces two different results

Screenshot included of the issue.
![screen shot 2015-01-16 at 3 47 48 pm](https://cloud.githubusercontent.com/assets/85320/5786270/2643fe72-9d97-11e4-8d13-0f2b0cb3f113.png)

**Comment by beporter** [comment]
This one is probably because I set debug=0 in the shell's main() to prevent spurious terminal output that would interfere with var capture.  Might need to figure out a special case for this.

**Comment by beporter** [comment]
We have two choices the way I see it:

1. ache the real value of `debug` to a class property in a new `::initialize()` method, then force debug off. We'll have to add a check specifically for if the key is `debug` and return the cached value instead.
2. Just remove the `Config::write(debug, 0)` altogether and let the chips fall as they may.

I'm leaning towards 2.
