### ISSUE TITLE
Look Into Removing `psy/psysh` dependency

### ISSUE THREAD

**Issue by justinyost** [loadsys/CakePHP-ConfigReadShell#28]

**Comment by beporter** [comment]
Pretty sure psysh isn't a direct dependency or ConfigReadShell. I think I included it here to avoid having to include it from the Shell-Scripts or something like that. I seriously can't think of any reason why it needs to be here.

If you wait a few days, I'd be happy to do a PR to remove it (and get credit for Hacktoberfest. ;-))
