### ISSUE TITLE
Adjust branches, update code/composer and tag new semver for Cake 3.

### ISSUE THREAD

**Issue by beporter** [loadsys/CakePHP-ConfigReadShell#3]
* [x] Branch the Cake 2.x compatible plugin into a `cake-2.x` branch, turn master into Cake 3.x compatible.
* [x] Update the plugin to work with Cake 3.
* [x] Update composer.json to be compatible with Cake 3 projects (the conflicting phpunit 3.7 dependency needs to go, for example.)
* [x] Release a new semver for `3.0.0`.

**Comment by jtyost2** [comment]
Closing as we have released a 3.x version of this.
